-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".municipios
(
    id serial NOT NULL,
    nome character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".bairros
(
    id serial NOT NULL,
    municipios_id integer NOT NULL,
    nome character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".ruas
(
    id serial NOT NULL,
    bairros_id integer NOT NULL,
    nome character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".secretarias
(
    id serial NOT NULL,
    nome character varying(100) NOT NULL,
    descricao character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".unidades
(
    id serial NOT NULL,
    secretarias_id integer NOT NULL,
    municipios_id integer NOT NULL,
    bairros_id integer NOT NULL,
    ruas_id integer NOT NULL,
    nome character varying(100) NOT NULL,
    telefone character(8) NOT NULL,
    descricao character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".departamentos
(
    id serial NOT NULL,
    secretarias_id integer NOT NULL,
    nome character varying(100) NOT NULL,
    descricao character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".funcionarios
(
    matricula character(6) NOT NULL,
    departamentos_id integer NOT NULL,
    cpf character(11) NOT NULL,
    nome character varying(100) NOT NULL,
    "nomeCompleto" character varying(255) NOT NULL,
    PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".status
(
    id serial NOT NULL,
    nome character varying(100) NOT NULL,
    descricao character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".tipos
(
    id serial NOT NULL,
    nome character varying(100) NOT NULL,
    descricao character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".equipamentos
(
    patrimonio character varying(6) NOT NULL,
    status_id integer NOT NULL,
    tipos_id integer NOT NULL,
    departamentos_id integer NOT NULL,
    funcionarios_matricula character(6) NOT NULL,
    unidades_id integer NOT NULL,
    observacao character varying(255),
    PRIMARY KEY (patrimonio)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".movimentacoes
(
    id serial NOT NULL,
    equipamentos_patrimonio character(6) NOT NULL,
    status_id integer NOT NULL,
    departamentos_id integer NOT NULL,
    funcionarios_matricula character(6) NOT NULL,
    data date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "tabelasInventarioMaquina".usuarios
(
    id integer NOT NULL,
    funcionarios_matricula character(6) NOT NULL,
    "tipoUsuario" bit NOT NULL,
    login character(100) NOT NULL,
    "senhaHash" character(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "tabelasInventarioMaquina".bairros
    ADD CONSTRAINT municipios_id FOREIGN KEY (municipios_id)
    REFERENCES "tabelasInventarioMaquina".municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".ruas
    ADD CONSTRAINT bairros_id FOREIGN KEY (bairros_id)
    REFERENCES "tabelasInventarioMaquina".bairros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".unidades
    ADD CONSTRAINT secretarias_id FOREIGN KEY (secretarias_id)
    REFERENCES "tabelasInventarioMaquina".secretarias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".unidades
    ADD CONSTRAINT municipios_id FOREIGN KEY (municipios_id)
    REFERENCES "tabelasInventarioMaquina".municipios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".unidades
    ADD CONSTRAINT bairros_id FOREIGN KEY (bairros_id)
    REFERENCES "tabelasInventarioMaquina".bairros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".unidades
    ADD CONSTRAINT ruas_id FOREIGN KEY (ruas_id)
    REFERENCES "tabelasInventarioMaquina".ruas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".departamentos
    ADD CONSTRAINT secretarias_id FOREIGN KEY (secretarias_id)
    REFERENCES "tabelasInventarioMaquina".secretarias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".funcionarios
    ADD CONSTRAINT departamentos_id FOREIGN KEY (departamentos_id)
    REFERENCES "tabelasInventarioMaquina".departamentos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".equipamentos
    ADD CONSTRAINT status_id FOREIGN KEY (status_id)
    REFERENCES "tabelasInventarioMaquina".status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".equipamentos
    ADD CONSTRAINT tipos_id FOREIGN KEY (tipos_id)
    REFERENCES "tabelasInventarioMaquina".tipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".equipamentos
    ADD CONSTRAINT departamentos_id FOREIGN KEY (departamentos_id)
    REFERENCES "tabelasInventarioMaquina".departamentos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".equipamentos
    ADD CONSTRAINT funcionarios_matricula FOREIGN KEY (funcionarios_matricula)
    REFERENCES "tabelasInventarioMaquina".funcionarios (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".equipamentos
    ADD CONSTRAINT unidades_id FOREIGN KEY (unidades_id)
    REFERENCES "tabelasInventarioMaquina".unidades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".movimentacoes
    ADD CONSTRAINT equipamentos_patrimonio FOREIGN KEY (equipamentos_patrimonio)
    REFERENCES "tabelasInventarioMaquina".equipamentos (patrimonio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".movimentacoes
    ADD CONSTRAINT status_id FOREIGN KEY (status_id)
    REFERENCES "tabelasInventarioMaquina".status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".movimentacoes
    ADD CONSTRAINT departamentos FOREIGN KEY (departamentos_id)
    REFERENCES "tabelasInventarioMaquina".departamentos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".movimentacoes
    ADD CONSTRAINT funcionarios_matricula FOREIGN KEY (funcionarios_matricula)
    REFERENCES "tabelasInventarioMaquina".funcionarios (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "tabelasInventarioMaquina".usuarios
    ADD CONSTRAINT funcionarios_matricula FOREIGN KEY (funcionarios_matricula)
    REFERENCES "tabelasInventarioMaquina".funcionarios (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;