-- Dados mínimos para o protótipo de autenticação.
-- Cria 1 secretaria, 1 departamento, 1 funcionário e 1 usuário de login.
--
-- Usuário de demonstração (login via banco, bcrypt):
--   login: fiscal   |   senha: fiscal123   |   tipoUsuario: 0 (usuário comum)
-- (O usuário "admin" NÃO fica no banco: usa o admin-fallback por env.)

SET search_path TO "tabelasInventarioMaquina";

-- Alguns status e tipos básicos de equipamento (úteis para evolução).
INSERT INTO status (nome, descricao) VALUES
  ('Disponível',       'Equipamento disponível'),
  ('Alocada',          'Equipamento alocado em uso'),
  ('Manutenção',       'Em manutenção'),
  ('Devolução',        'Equipamento devolvido'),
  ('Aguardando',       'Chamado aguardando atendimento'),
  ('Em manutenção',    'Chamado em manutenção'),
  ('Entregue',         'Chamado entregue/finalizado');

INSERT INTO tipos (nome, descricao) VALUES
  ('Desktop',   'Computador de mesa'),
  ('Notebook',  'Computador portátil'),
  ('Monitor',   'Monitor de vídeo'),
  ('Impressora','Impressora'),
  ('Estabilizador', 'Estabilizador de tensão'),
  ('Nobreak',   'Nobreak / UPS'),
  ('Tablet',    'Tablet'),
  ('Servidor',  'Servidor'),
  ('Switch',    'Switch de rede'),
  ('Roteador',  'Roteador de rede'),
  ('Projetor',  'Projetor / Data show'),
  ('TV',        'Televisor'),
  ('Scanner',   'Scanner'),
  ('Teclado',   'Teclado'),
  ('Mouse',     'Mouse'),
  ('Webcam',    'Câmera webcam');

-- Secretarias da prefeitura (seed para selects).
INSERT INTO secretarias (nome, descricao) VALUES
  ('Secretaria de Administração',          'Administração geral'),
  ('Secretaria de Educação',               'Educação e ensino'),
  ('Secretaria de Saúde',                  'Saúde pública'),
  ('Secretaria de Assistência Social',     'Assistência e desenvolvimento social'),
  ('Secretaria de Finanças',               'Finanças e tributação'),
  ('Secretaria de Obras',                  'Obras e infraestrutura'),
  ('Secretaria de Esportes',               'Esportes e lazer'),
  ('Secretaria de Cultura',                'Cultura e turismo'),
  ('Secretaria de Segurança',              'Segurança cidadã'),
  ('Secretaria de Meio Ambiente',          'Meio ambiente e sustentabilidade'),
  ('Secretaria de Planejamento',           'Planejamento urbano'),
  ('Secretaria de Transporte',             'Transporte e mobilidade'),
  ('Gabinete do Prefeito',                 'Gabinete executivo');

-- Hierarquia mínima para satisfazer as FKs de funcionarios/usuarios.
WITH sec AS (
  INSERT INTO secretarias (nome, descricao)
  VALUES ('Secretaria de Tecnologia', 'Seed inicial')
  RETURNING id
), dep AS (
  INSERT INTO departamentos (secretarias_id, nome, descricao)
  SELECT id, 'GECOTEC', 'Seed inicial' FROM sec
  RETURNING id
)
INSERT INTO funcionarios (matricula, departamentos_id, cpf, nome, "nomeCompleto")
SELECT '100001', id, '00000000000', 'Fiscal', 'Fiscal de Inventário' FROM dep;

-- Usuário de login (senha "fiscal123" com bcrypt).
INSERT INTO usuarios (id, funcionarios_matricula, "tipoUsuario", login, "senhaHash")
VALUES (
  1,
  '100001',
  B'0',
  'fiscal',
  '$2a$10$dWq676YK3oD0q1c.Gz5wLOkB0mHBgZLMkk786DaePIQCMTuVAmkZ6'
);

-- Localização (cadeia municipios -> bairros -> ruas) para a tela de Unidades.
INSERT INTO municipios (nome) VALUES ('Francisco Morato');
INSERT INTO bairros (municipios_id, nome)
  VALUES ((SELECT id FROM municipios WHERE nome = 'Francisco Morato'), 'Centro');
INSERT INTO ruas (bairros_id, nome)
  VALUES ((SELECT id FROM bairros WHERE nome = 'Centro'), 'Rua Principal');

-- 1 unidade (satisfaz as FKs de equipamentos.unidades_id).
INSERT INTO unidades (secretarias_id, municipios_id, bairros_id, ruas_id, nome, telefone, descricao, cep, endereco)
VALUES (
  (SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'),
  (SELECT id FROM municipios   WHERE nome = 'Francisco Morato'),
  (SELECT id FROM bairros      WHERE nome = 'Centro'),
  (SELECT id FROM ruas         WHERE nome = 'Rua Principal'),
  'Sede', '32010000', 'Unidade sede', '07900000', 'Rua Principal, 100 - Centro'
);

-- 1 equipamento de exemplo (deixa a tela de Máquinas não-vazia).
INSERT INTO equipamentos (patrimonio, status_id, tipos_id, departamentos_id, funcionarios_matricula, unidades_id, observacao, data_alocacao, data_devolucao)
VALUES (
  '000001',
  (SELECT id FROM status        WHERE nome = 'Disponível'),
  (SELECT id FROM tipos         WHERE nome = 'Desktop'),
  (SELECT id FROM departamentos WHERE nome = 'GECOTEC'),
  '100001',
  (SELECT id FROM unidades      WHERE nome = 'Sede'),
  'Equipamento de exemplo',
  NULL,
  NULL
);

-- Departamentos da prefeitura (seed para selects e listagens).
INSERT INTO departamentos (secretarias_id, nome, descricao) VALUES
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamentos da prefeitura', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Tecnologia Interna/Informática', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Comunicação', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de ODS -IEG-M', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Gestão Administrativa', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Relações Públicas e Organizacionais', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Controladoria', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Ouvidoria', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Divisão de Transparência da Administração Municipal', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Procuradoria do Município', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Procedimentos Administrativos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento Jurídico', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Atos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Gabinete do Secretário Adjunto', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'INSS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Cerimonial', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Relações Institucionais', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Assuntos Estratégicos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Fundo de Ação e Economia Solidária', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Defesa Civil', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Licitações', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Administração Patrimonial', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Divisão de Apoio Técnico e Operacional', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Controle de Processos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Gestão Financeira', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Projetos e Parcerias', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Gestão de Pessoas', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Planejamento', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Fundo - RPPS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento da Guarda Civil Municipal', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Divisão de Vigilância Patrimonial', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Atendimento Central', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Trânsito e Mobilidade', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Trabalho, Indústria e Comércio', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Atividade Compartilhada de Inteligência', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Tributos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Habitação', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Regularização Fundiária e Fiscalização e Proteção de Áreas Públicas', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Arrecadação e Dívida Ativa', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento do Meio Ambiente, Clima e Energia', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Fiscalização', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Defesa das Relações de Consumo', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Gerenciamento de Obras', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Vigilância Socioassistencial', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Gerenciamento de Infraestrutura Urbana', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Proteção Social Especial', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Proteção Social Básica', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Serviços Urbanos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Garantias Cidadãs', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Urbanismo', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Infraestrutura', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Educação Infantil', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Ensino Fundamental', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Programas e Projetos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Alimentação Escolar', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Cultura', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Incentivo ao Turismo', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Planejamento de Políticas Públicas, Culturais e Turísticas', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Equipamentos Esportivos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Projetos Esportivos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Formação e Rendimento', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Atividades Físicas (Recreação e Lazer)', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL JOSE BEZERRA SANCHES PREFEITO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL MACHADO DE ASSIS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL DOUTOR FRANCISCO MORATO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ANISIO SPINOLA TEIXEIRA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL BRIGADEIRO ROBERTO BRANDINI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL CARLOS DRUMMOND DE ANDRADE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL VANDA TERESINHA NALIN', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL EGON SCHADEN', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ULISSES SILVEIRA GUIMARAES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF. SANDRA REGINA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ELBA NOBREGA SOBRAL', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL RADIALISTA JAIME GONÇALVES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF. LAIRCE LUPIANHA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF TANIA FERNANDES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ERICO VERISSIMO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PAULO FREIRE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PADRE LUIZ SERGIO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL FANNY GOLDBERG', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL GIULIANO CECCHETTINI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ISABEL LUPIANHES ROMERA RYAN', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ALFREDO VOLPI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF. ELIANE MARIA DE PAULA OLIVEIRA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ALMEIDA JUNIOR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL VEREADOR AMADO PINTO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ANITA MALFATTI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ANTONIO FEDERZONI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ANTONIO MUNIZ', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL CANDIDO PORTINARI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL CASTRO ALVES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL CLARICE LISPECTOR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL EDITE PEREIRA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL FERNANDO PESSOA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL GRACILIANO RAMOS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL JOAO GUIMARAES ROSA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL LEONARDO DA VINCI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL LIMA BARRETO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL MONTEIRO LOBATO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL OLAVO BILAC', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF. SONIA REGINA F. DE OLIVEIRA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL VINICIUS DE MORAES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL RUTH ROCHA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL TARSILA DO AMARAL', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL TATIANA BELINK', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ZELIA GATTAI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL ANTONIO PACHECO DO NASCIMENTO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL CORA CORALINA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF. HELY MARA DA SILVA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL VEREADOR HEITOR HARTMANN', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL PROF HOSUE MORITA AOKI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CRAS JARDIM ALEGRIA/ REGIONAL JD ALEGRIA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CRAS 120', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CRAS SANTO ANTONIO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CENTRO POP', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CENTRO SOCIAL URBANO / ESPORTES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CREAS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'FUNDO SOCIAL DE SOLIDARIEDADE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'UNID. POLO DE FORMAÇÃO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CARTÓRIO ELEITORAL 367', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CRAS VASSOURAS II', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'ARQUIVO MORTO / PATRIMÔNIO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CRAS BELEM ESTAÇÃO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'ALMOXARIFADO CENTRAL', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'PROCON', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'GARAGEM OFICINA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CONSELHO TUTELAR II', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'SECRETARIA DA CULTURA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'DELEGACIA DA MULHER', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'UNIVESP - LABORATORIO DE INFORMATICA VL HELOISA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'AUDITÓRIO LAURA BRESSANE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'IBGE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'FUSBEMO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO AGUA VERMELHA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF CASA GRANDE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DR WALFRIDO TIBURCIO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO ARPOADOR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO JARDIM NOVA ESPERANÇA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO JARDIM ROSAS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO JARDIM SILVIA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO PARQUE PAULISTA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO JARDIM SANTO ANTONIO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF TEREZINHA MARQUES DA SILVA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF VILA GUILHERME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF JD BATISTA GENARI', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'USF DO PQ 120', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Vigilância Sanitária', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Almoxarifado - SAME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Farmacia central', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Caps II Centro', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Transportes', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Caps Infantil', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CEO - Centro Odontologia', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CAPS AD Ana Marques', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'C.T.A', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Ambulatório', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Fisioterapia', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Casa da Mulher', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Compras', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Núcleo de Atendimento às Vítimas de Violência', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento De Execução Fiscal', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Contabilidade', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Oficina Pedagogica', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'RH-SAME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Programas e Projetos', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Cadastro', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Vida Escolar', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Secretaria de Segurança Cidadã', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Protocolo', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Atenção Básica', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Financeiro - SAME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de ISS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Receitas', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Políticas Públicas Setoriais e de Direitos, Programas e Projetos.', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'STARTUP', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Supervisão Educação', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M DE ENSINO FUNDAMENTAL MARCO AURÉLIO DOMINGOS MAGOGA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Transporte Escolar', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'AMEM', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'LGBTQIA+', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'SEBRAE - Serviço Brasileiro de Apoio às Micro e Pequenas Empresas', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Casa Afro', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M de Ensino Infantil Jorge Tertuliano Rizzi', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'RH - Educação', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'GALPÃO PROGRESSO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M de Ensino Infantil Vereador Pastor Jorge Gabriel Rodrigues', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'BOLSA FAMILIA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'CONSELHO TUTELAR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Zoonoses', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'UPA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Junta Militar de Fco. Morato', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Gabinete da Educação', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Gabinete Assistência e Desenvolvimento Social', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Compras - SAME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Regulação - SAME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Gabinete do(a) Prefeito(a)', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Secretaria de Esportes', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'E M ALAIN DOS SANTOS GOMES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de T.I. - SAME', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'FROTA ESCOLAR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Parque Da Criança - Esporte e Lazer', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Gestão Financeira - CONCENTRADOR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO SANTO ANTONIO', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO JARDIM ALEGRIA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO JARDIM ROSAS / SANTA CASA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO CASA GRANDE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO TERMINAL LESTE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO TERMINAL OESTE', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO REGIAO CENTRAL I / TRAVESSA BOULEVARD', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO CSU', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO PRACA BELEM DA SERRA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO PARQUE 120', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO REGIAO CENTRAL II / PRACA CASSIANO PASSOS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO JARDIM VASSOURAS / MAGDALENA SHILLER', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO REGIAO CENTRAL III / CIC', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO PARQUE DA CRIANCA', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'QUADRA DE ESPORTES - EMEC', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'WIFI-PUBLICO CEU DAS ARTES', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'EM DE ENSINO INFANTIL ORDÁRIO DE SOUZA MARTINS', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'MERENDA ESCOLAR', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Tesouraria', NULL),
  ((SELECT id FROM secretarias WHERE nome = 'Secretaria de Tecnologia'), 'Departamento de Serviços On Line', NULL);
